#!/bin/bash

#
# /etc/xdg/pacaur/config
#

# The following options are commented out with their default values listed.
# If you wish to use different values, uncomment and update the values.
# The Color and VerbosePkgLists options can be enabled in /etc/pacman.conf.
# The clone directory can be changed through the $AURDEST environment variable.
# The makepkg environment variables are also fully honored.
#editor="${EDITOR:-vi}"                # build files editor
#displaybuildfiles=full                # display build files (none|diff|full)
#fallback=true                         # pacman fallback to the AUR
#silent=false                          # silence output
#sortby=popularity                     # sort method (name|votes|popularity)
#sudoloop=false                        # prevent sudo timeout

