#!/bin/bash

#
# /etc/xdg/pacaur/config
#

# The following options are commented out with their default values listed.
# If you wish to use different values, uncomment and update the values.
# The Color and VerbosePkgLists options can be enabled in /etc/pacman.conf.
#clonedir="${AURDEST:-$tmpdir}"        # clone directory
#editor="${EDITOR:-vi}"                # PKGBUILD editor
#editpkgbuild=true                     # edit PKGBUILD and install scripts
#fallback=true                         # pacman fallback to the AUR
#clean=true                            # clean up after package install
#cleandevel=true                       # clean up devel package
#silent=false                          # silence output
#sortby=popularity                     # sort method (name|votes|popularity)
#sudoloop=false                        # prevent sudo timeout

