#!/bin/bash

#
# pacaur: A fast workflow AUR helper using cower
#

name="pacaur"
version="2.0.0"
description="A fast workflow AUR helper using cower"

#
# Default config
#

pacmanBin="pacman-color"        # pacman binary
editor=${EDITOR:-vi}            # PKGBUILD editor
buildDir=/home/aur/build        # build directory
clean=true                      # cleanup after install
fallback=true                   # pacman fallback
color=true                      # enable color

tmpDir="${TMPDIR:-/tmp}/${name}tmp-$USER"

colorR="\e[1;31m"
colorG="\e[1;32m"
colorY="\e[1;33m"
colorB="\e[1;34m"
colorM="\e[1;35m"
colorC="\e[1;36m"
colorW="\e[1;37m"

#
# Source user config
#

source /etc/${name}.conf

#
# Color
#

if $color; then
    cower='cower --color=always'
    bold=$(tput bold)
    reset=$(tput sgr0)
else
    cower='cower'
    bold=''
    reset=''
    colorR=''
    colorG=''
    colorY=''
    colorB=''
    colorM=''
    colorC=''
    colorW=''
fi

#
# Functions
#

runasroot() {
    if [[ $UID -eq 0 ]]; then
        "$@"
    elif sudo -v &>/dev/null && sudo -l "$@" &>/dev/null; then
        sudo "$@"
    else
        echo -n "root "
        # echo hack to ensure all of the args get taken into account
        su root -c "$(echo $@)"
    fi
}

SearchAur() {
    $cower -s $@
}

InfoAur() {
    $cower -i $@
}

InfoDetailsAur() {
    $cower -ii $@
}

DownloadAur() {
    if [[ ! $force ]]; then
        $cower -d $@ -t $buildDir
    else
        $cower -d -f $@ -t $buildDir
    fi
}

DownloadDepsAur() {
    # download dependencies recursively and return AUR deps only
    if [[ ! $force ]]; then
        deps=$($cower -dd $@ -t $buildDir | tee 1>&2 >(awk -F " " '{print $2}'| sed -r "s:\x1B\[[0-9;]*[mK]::g"))
    else
        deps=$($cower -dd -f $@ -t $buildDir | tee 1>&2 >(awk -F " " '{print $2}'| sed -r "s:\x1B\[[0-9;]*[mK]::g"))
    fi

    ErrorExit $deps
}

FindDepsAur() {
    # set tmpdir
    mkdir -p "$tmpDir"

    # check dependencies recursively and return AUR deps only
    deps=$($cower -dd $@ -t $tmpDir | tee 1>/dev/null >(awk -F " " '{print $2}'| sed -r "s:\x1B\[[0-9;]*[mK]::g"))

    ErrorExit $deps

    # clean tmpdir
    rm -rf "$tmpDir" &>/dev/null
}

CheckAur() {
    $cower -u $@
}

CheckRepo() {
    outofdate=($($pacmanBin -Quq $@))
    if [[ ${outofdate[@]} != "" ]]; then
        Qversion=($(expac -Q %v ${outofdate[@]}))
        Sversion=($(expac -S -1 %v ${outofdate[@]}))

        local i=0
        for package in ${outofdate[@]}; do
            notice "${colorW}${outofdate[$i]} ${colorR}${Qversion[$i]} ${reset}-> ${colorG}${Sversion[$i]}${reset}"
            ((i++))
        done
    fi
}

UpgradeAur() {
    notice "${colorW}Starting AUR upgrade...${reset}"
    pkgs=$($cower -u $@ | tee 1>&2 >(awk -F " " '{print $2}'| sed -r "s:\x1B\[[0-9;]*[mK]::g"))

    # add devel packages
    if [[ $devel ]]; then
        aurpkgs=( $($pacmanBin -Qmq) )
        Qversion=($(expac -Q %v ${aurpkgs[@]}))

        # set tmpdir
        mkdir -p "$tmpDir"

        local i=0
        for package in ${aurpkgs[@]}; do
            DownloadPkgbuild ${aurpkgs[$i]} &
            ParaExec
            ((i++))
        done
        wait
        local j=0
        for package in ${aurpkgs[@]}; do
            unset _darcstrunk _cvsroot _gitroot _svntrunk _bzrtrunk _hgroot
            . "$tmpDir/$package.PKGBUILD"
            if [[ ${_darcstrunk} || ${_cvsroot} || ${_gitroot} || ${_svntrunk} || ${_bzrtrunk} || ${_hgroot} ]]; then
                aurdevel=("${aurdevel[@]}" "${aurpkgs[$j]}")
                notice "${colorW}${aurpkgs[$j]} ${colorY}${Qversion[$j]} ${reset}"
            fi
            ((j++))
        done

        # clean tmpdir
        rm -rf "$tmpDir" &>/dev/null

        pkgs=("${pkgs[@]}" "${aurdevel[@]}")
        pkgs=$(echo ${pkgs[@]} | awk -F "\n" '{print}' | awk -F " " '{print}')
    fi

    if [[ $pkgs == "" ]]; then
        echo " there is nothing to do"
        exit   
    fi

    ErrorExit $pkgs

    echo -e "\nProceed with installation? [Y/n]"
    
    while true; do
        read yn
        case $yn in
        [Yy]* | Yes | yes)
            pkgs=${pkgs}
            break
        ;;
        [Nn]* | No | no)
            exit
            break
        ;;
        *)
            exit
            break
        ;;
        esac
    done
}

CopyAbs() {
    for i in "$@"
    do
        if [[ -e $buildDir/$i/PKGBUILD && ! $force ]]; then
            failed "${colorW}$i${reset} PKGBUILD already exists in $buildDir. Use -f to overwrite."
        else
            cp -r `find /var/abs -name "$i"` $buildDir || error "${colorW}$i${reset} not found"
            success "${colorW}$i${reset} copied in $buildDir"
        fi
    done
}

EditPkgs() {
    if [[ $edit ]]; then
    for i in "$@"
    do
        if [ -e $buildDir/$i/PKGBUILD ]; then
            $editor $buildDir/$i/PKGBUILD
            success "${colorW}$i${reset} PKGBUILD edited"
        else
            error "Could not open ${colorW}$i${reset} PKGBUILD"
        fi
    done
    fi
}

CleanUp() {
    if [[ $clean == true ]]; then
        cd $buildDir
        for i in $@
        do
            notice "Cleaning up ${colorW}$i${reset}... "
            # hack for cvs protected files
            chmod -R 755 $i &>/dev/null
            rm -r $i && success "${colorW}$i${reset} cleaned" || failed "Could not clean ${colorW}$i${reset}"
        done
    fi
}

MakePkgs() {
    # reverse deps order
    deps=($(echo ${deps[@]} | awk -F "\n" '{print}' | awk -F " " '{for (i=NF;i>=1;i--) print $i}'))
    notice "AUR package(s) to build: ${colorW}${deps[@]}${reset}"

    # remember explicitly installed packages
    if [[ $expl == "" ]]; then
      read -ra expl <<< ${pkgs[@]}
    fi

    # set architecture variables
    if [[ ! $confSourced ]]; then
        source /etc/makepkg.conf
        source /etc/abs.conf
        confSourced=true
    fi

    # allow build as root
    if [[ $asroot ]]; then
        makepkg='makepkg --asroot'
    else
        makepkg='makepkg'
    fi

    local j
    for j in "${deps[@]}"
    do
        if [ -e $buildDir/$j/PKGBUILD ]; then
            notice "Building ${colorW}$j${reset} package..."
            cd $buildDir/$j
            if [[ $install ]]; then
                $makepkg -sfi
                # if AUR dep, install as --asdeps
                # if upgrade, do no change status
                if [[ ! $upgrade ]]; then
                    isexpl=false
                    for k in ${expl[@]}; do
                        if [[ $k == $j ]]; then
                            isexpl=true
                        fi
                    done
                    if [[ $isexpl != true ]]; then
                        runasroot $pacmanBin -D --asdeps $j &>/dev/null
                    fi
                fi
            else
                $makepkg -sf
            fi
        else
            error "Could not open ${colorW}$j${reset} PKGBUILD"
        fi
    done
}

DownloadPkgbuild() {
    if ! [[ -f "$tmpDir/$package.PKGBUILD" ]]; then
        curl -Lfs "https://aur.archlinux.org/packages/$package/PKGBUILD" > "$tmpDir/$package.PKGBUILD"
    fi
}

ParaExec() {
    while (( $(jobs | wc -l) >= 10 )); do
        sleep 0.1
        jobs > /dev/null
    done
}

ErrorExit(){
    if [[ $(echo $@ | grep -v "Couldn't resolve host name" | grep -v "no results found for") == "" ]]; then 
        exit
    fi
}

error() {
    echo -e "${colorR}::${reset} $1"
    exit
}

success() {
    echo -e "${colorG}::${reset} $1"
}

failed() {
    echo -e "${colorY}::${reset} $1"
}

notice() {
    echo -e "${colorB}::${reset} $1"
}

usage() {
    echo "usage:  ${name} <operation> [options] [package(s)]"
    echo "operations:"
    echo "   -s, --search    search AUR repository for matching strings"
    echo "   -i, --info      view package information -- pass twice for details"
    echo "   -d, --download  download target(s) -- pass twice to download AUR dependencies"
    echo "   -b, --build     use existing PKGBUILD and make target(s)"
    echo "   -m, --makepkg   download and make target(s)"
    echo "   -y, --sync      download, make and install target(s)"
    echo "   -q, --check     check for AUR update(s)"
    echo "   -u, --update    update AUR package(s)"
    echo "   -abs, --abs     copy target(s) from ABS directory to build directory"
    echo ""
    echo "options:"
    echo "   -f, --force     force operation -- can be combined with the -d, -m, -y, -abs flags"
    echo "   -e, --edit      edit target PKGBUILD -- can be combined with the -d, -b, -m, -y, -u, -abs flags"
    echo "   -c, --clean     clean existing target(s) PKGBUILD -- can be combined with the -b, -m, -y, -abs flags"
    echo ""
    echo "pacman options:"
    echo " can be used with the -S, -Ss, -Si, -Sii, -Sw, -Su, -Qu, -Syu operations"
    echo "   -r, --repo      only search or install packages from the repositories"
    echo "   -a, --aur       only search or install packages from the AUR"
    echo "   --devel         update AUR devel packages -- can be combined with the -Su flag"
    echo ""
    echo "general options:"
    echo "   -v, --version   display version information"
    echo "   -h, --help      display help information"
    echo ""
    exit
}

version() {
    echo -e "\n    ${colorW}$name ${colorG}$version${reset}"
    echo -e "    $description\n"
}


#
# Argument parsing
#

[[ $1 ]] || usage
pkgs=()
count=0
while [[ $1 ]]; do
    case "$1" in
        '-s'|'--sync') operation=search ;;
        '-i'|'--info') operation=info; count=$[$count+1] ;;
        '-d'|'--download') operation=download; count=$[$count+1] ;;
        '-b'|'--build') operation=build ;;
        '-m'|'--makepkg') operation=makepkg ;;
        '-y'|'--sync') operation=makepkg ; install=true ;;
        '-q'|'--check') operation=check ;;
        '-u'|'--update') operation=makepkg; upgrade=true; force=true; install=true ;;
        '-abs'|'--abs') operation=abs ;;
        '-c'|'--clean') clean=true ;;
        '-f'|'--force') force=true ;;
        '-e'|'--edit') edit=true ;;
        # shortcuts
        '-ii') operation=info; count='2' ;;
        '-dd') operation=download; count='2' ;;
        '-df') operation=download; count=$[$count+1]; force=true ;;
        '-de') operation=download; count=$[$count+1]; edit=true ;;
        '-def'|'-dfe') operation=download; count=$[$count+1]; edit=true; force=true ;;
        '-ddf') operation=download; count='2'; force=true ;;
        '-dde') operation=download; count='2'; edit=true ;;
        '-ddef'|'-ddfe') operation=download; count='2'; edit=true; force=true ;;
        '-be') operation=build; edit=true ;;
        '-me') operation=makepkg; edit=true ;;
        '-mf') operation=makepkg; force=true ;;
        '-mef'|'-mfe') operation=makepkg; force=true; edit=true ;;
        '-ye') operation=makepkg; edit=true; install=true ;;
        '-yf') operation=makepkg; force=true; install=true ;;
        '-yfe'|'-yef') operation=makepkg; force=true; edit=true; install=true ;;
        '-ue') operation=makepkg; upgrade=true; force=true; edit=true; install=true ;;
        '-abse') operation=abs; edit=true ;;
        '-absf') operation=abs; force=true ;;
        '-absef'|'-absfe') operation=abs; force=true; edit=true ;;
        # pacman
        '-S'|'--sync') option=sync; install=true; force=true; edit=true ;;
        '-Ss'|'--search') option=search ;;
        '-Si'|'--info') option=info; count=$[$count+1] ;;
        '-Sii'|'--info') option=info; count='2' ;;
        '-Sw'|'--downloadonly') option=sync; force=true; edit=true ;;
        '-Qu'|'--upgrades') option=upgrades ;;
        '-Su'|'--sysupgrade'|'-Syu'|'-Suy'|'-Syyu'|'-Suyy'|'-Syuy'|'-Syuu'|'-Suuy'|'-Suu'|'-Syyuu'|'-Suuyy'|'-Syuy'|'-Syuyu'|'-Syuuy'|'-Suyuy')
              option=sysupgrade; upgrade=true; force=true; edit=true; install=true; pacmanarg="$1" ;;
        '-r'|'--repo') repo='1' ;;
        '-a'|'--aur') aur='1' ;;
        # pacman shortcuts
        '-Sa') option=sync; install=true; force=true; edit=true; aur='1' ;;
        '-Sr') option=sync; install=true; force=true; edit=true; repo='1' ;;
        '-Ssa') option=search; aur='1' ;;
        '-Ssr') option=search; repo='1' ;;
        '-Sia') option=info; count=$[$count+1]; aur='1' ;;
        '-Sir') option=info; count=$[$count+1]; repo='1' ;;
        '-Siia') option=info; count='2'; aur='1' ;;
        '-Siir') option=info; count='2'; repo='1' ;;
        '-Swa') option=sync; force=true; edit=true; aur='1' ;;
        '-Swr') option=sync; force=true; edit=true; repo='1' ;;
        '-Qua') option=upgrades; aur='1' ;;
        '-Qur') option=upgrades; repo='1' ;;
        '-Sua'|'-Syua'|'-Suya'|'-Syyua'|'-Suyya'|'-Syuya'|'-Syuua'|'-Suuya'|'-Suua'|'-Syyuua'|'-Suuyya'|'-Syuya'|'-Syuyua'|'-Syuuya'|'-Suyuya')
              option=sysupgrade; upgrade=true; force=true; edit=true; install=true; pacmanarg="$1"; aur='1' ;;
        '-Sur'|'-Syur'|'-Suyr'|'-Syyur'|'-Suyyr'|'-Syuyr'|'-Syuur'|'-Suuyr'|'-Suur'|'-Syyuur'|'-Suuyyr'|'-Syuyr'|'-Syuyur'|'-Syuuyr'|'-Suyuyr')
              option=sysupgrade; upgrade=true; force=true; edit=true; install=true; pacmanarg="$1"; repo='1' ;;
        # others
        '--devel') devel=true ;;
        '--asroot') asroot=true ;;
        -D* | '--database') runasroot $pacmanBin $@; exit ;;
        -Q* | '--query') $pacmanBin $@; exit ;;
        -R* | '--remove') runasroot $pacmanBin $@; exit ;;
        -S* | '--sync') runasroot $pacmanBin $@; exit ;;
        -T* | '--deptest') runasroot $pacmanBin $@; exit ;;
        -U* | '--upgrade') runasroot $pacmanBin $@; exit ;;
        --*) runasroot $pacmanBin $@; exit ;;
        '-h'|'--help') usage; exit ;;
        '-v'|'--version') version; exit ;;
        -*) echo "$name: invalid option -- '$1'" ; exit ;;
        *) pkgs+=("$1") ;;
    esac
    shift
done


#
# Main
#

Core() {
    DownloadDepsAur ${pkgs[@]}
    EditPkgs ${deps[@]}
    MakePkgs ${deps[@]}
    CleanUp ${deps[@]}
}

# sanity check
if [[ ! -d $buildDir ]]; then
  error "Build directory does not exist!\nCheck configuration in /etc/${name}.conf"
fi
if [[ ! -f /usr/bin/$pacmanBin ]]; then
  error "Pacman binary does not exist!\nCheck configuration in /etc/${name}.conf"
fi

# search (-s) handling
if [[ $operation = search ]]; then
    SearchAur ${pkgs[@]}
    exit
fi

# info (-i) handling
if [[ $operation = info ]]; then
    [[ $count -eq 1 ]] && InfoAur ${pkgs[@]} || InfoDetailsAur ${pkgs[@]}
    exit
fi

# download (-d) handling
if [[ $operation = download ]]; then
    [[ $count -eq 1 ]] && DownloadAur ${pkgs[@]} || DownloadDepsAur ${pkgs[@]}
    [[ ! $deps ]] && deps=("${pkgs[@]}")
    EditPkgs ${deps[@]}
    exit
fi

# build (-b) handling
if [[ $operation = build ]]; then
    FindDepsAur ${pkgs[@]}
    [[ ! $deps ]] && deps=("${pkgs[@]}")
    EditPkgs ${deps[@]}
    MakePkgs ${deps[@]}
    CleanUp ${deps[@]}
    exit
fi

# makepkg (-m) handling
# sync (-y) handling
# update (-u) handling
if [[ $operation = makepkg ]]; then
    [[ $upgrade ]] && UpgradeAur
    Core ${pkgs[@]}
    exit
fi

# check (-q) handling
if [[ $operation = check ]]; then
    CheckAur ${pkgs[@]}
    exit
fi

# abs (-abs) handling
if [[ $operation = abs ]]; then
    CopyAbs ${pkgs[@]}
    EditPkgs ${pkgs[@]}
    exit
fi

# edit (-e) handling
if [[ $edit && ! $option ]]; then
    EditPkgs ${pkgs[@]}
    exit
fi

# clean (-c) handling
if [[ $clean && ! $option ]]; then
    CleanUp ${pkgs[@]}
    exit
fi

# pacman sync (-S) handling
# pacman downloadonly (-Sw) handling
if [[ $option = sync ]]; then
    [[ ! $aur ]] && result=$($pacmanBin -S --print ${pkgs[@]} 2>&1)
    if [[ $(echo $result | grep -v "error: target not found") == "" ]]; then
        if [[ $fallback = true ]]; then
            [[ ! $aur ]] && [[ ! $repo ]] && failed "Package(s) ${colorW}${pkgs[@]}${reset} not found in repositories, trying ${colorM}aur${reset}..."
            [[ ! $repo ]] && Core ${pkgs[@]}
            [[ $repo ]] && error "no results found for ${colorW}${pkgs[@]}${reset}"
        else
            [[ $aur ]] && Core ${pkgs[@]} || error "no results found for ${colorW}${pkgs[@]}${reset}"
        fi
    else
        [[ ! $aur ]] && [[ $install ]] && runasroot $pacmanBin -S ${pkgs[@]} || [[ ! $aur ]] && [[ ! $install ]] && runasroot $pacmanBin -Sw ${pkgs[@]}
    fi
    exit
fi

# pacman search (-Ss) handling
if [[ $option = search ]]; then
        [[ ! $aur ]] && $pacmanBin -Ss ${pkgs[@]}
        if [[ $fallback = true ]]; then
            [[ ! $repo ]] && SearchAur ${pkgs[@]}
        else
            [[ $aur ]] && SearchAur ${pkgs[@]}
        fi
    exit
fi

# pacman info (-Si) handling
if [[ $option = info ]]; then
    [[ ! $aur ]] && result=$($pacmanBin -Si --print ${pkgs[@]} 2>&1)
    if [[ $(echo $result | grep -v "error: package") == "" ]]; then
        if [[ $fallback = true ]]; then
            [[ ! $aur ]] && [[ ! $repo ]] && failed "Package(s) ${colorW}${pkgs[@]}${reset} not found in repositories, trying ${colorM}aur${reset}..."
            [[ ! $repo ]] && InfoAur ${pkgs[@]}
            [[ $repo ]] && error "no results found for ${colorW}${pkgs[@]}${reset}"
        else
            [[ $aur ]] && InfoAur ${pkgs[@]} || error "no results found for ${colorW}${pkgs[@]}${reset}"
        fi
    else
        [[ ! $aur ]] && $pacmanBin -Si ${pkgs[@]}
    fi
    exit
fi

# pacman sysupgrade (-Su) handling
# pacman refresh (-Sy) handling
if [[ $option = sysupgrade ]]; then
    [[ ! $aur ]] && runasroot $pacmanBin "$pacmanarg"
    if [[ $fallback = true ]]; then
        [[ ! $repo ]] && [[ $upgrade ]] && UpgradeAur
        [[ ! $repo ]] && Core ${pkgs[@]}
    else
        [[ $aur ]] && [[ $upgrade ]] && UpgradeAur
        [[ $aur ]] && Core ${pkgs[@]}
    fi
    exit
fi

# pacman upgrades (-Qu) handling
if [[ $option = upgrades ]]; then
    [[ ! $aur ]] && CheckRepo ${pkgs[@]}
    if [[ $fallback = true ]]; then
        [[ ! $repo ]] && CheckAur ${pkgs[@]}
    else
        [[ $aur ]] && CheckAur ${pkgs[@]}
    fi
    exit
fi

# vim:set ts=4 sw=2 et:
