=encoding utf8

=head1 NAME

pacaur - a fast workflow AUR helper using cower as backend

=head1 SYNOPSIS

Usage: I<pacaur> E<lt>operationE<gt> [ options ] [ package(s) ]

=head1 DESCRIPTION

Pacaur is an Arch User Repository (AUR) helper aiming at speed and simplicity,
designed to minimize user prompt interaction and to use an uncluttered
interface. It is built upon the well designed cower and expac C backends.
Invoking pacaur consists of supplying an operation, any applicable options, and
usually one or more targets.

=head1 USERBASE TARGET

Pacaur is targeted at B<advanced users> who want some degree of automation for
repetitive tasks. As such, the user is expected to be familiar with the AUR
manual build process with makepkg as well as being knownledgeable about sudo
configuration.

Two sets of command line options are provided: commands which call the pacman
binary and extend for AUR functions B<(-S, -Q)>, and commands which are AUR
specific B<(-s, -i, -d, -m, -y, -k, -u)>. As such, pacaur can be used by users
who prefer to have a single tool to manage officials and AUR repositories, or by
users who prefer to keep their AUR frontend separated from pacman.

=head1 OPERATIONS

=over 4

=item B<-S, -Ss, -Si, -Sii, -Sw, -Su, -Qu, -Sc, -Scc>

Pacaur wraps B<pacman operations> and extends respectively its install, search,
info, download, update, check updates and clean functions to the AUR. This
behavior is optional and can be disabled with the I<fallback> variable in the
config file. Pacaur will also pass any pacman related options to the pacman
binary.

=item B<-s, --search>

Search for packages with the I<target>(s) as the search term(s). Queries with
multiple targets will return the result of the intersection of all query
results. Extended regex patterns as defined by POSIX are allowed.

=item B<-i, --info>

Show info for I<target>. Pass this option twice to fetch more detailed info.

=item B<-d, --download>

Download I<target>(s) PKGBUILD. Pass this option twice to fetch dependencies
(done recursively).

=item B<-m, --makepkg>

Download I<target>(s) PKGBUILD and build target(s). Missing dependencies will be
installed as required to ensure the build to succeed, before being automatically
uninstalled.

=item B<-y, --sync>

Download I<target>(s) PKGBUILD, build and install target(s). Missing
dependencies will be automatically installed as required.

=item B<-k, --check>

Check foreign packages for updates in the AUR. Without any arguments, all
manually installed packages will be checked. If targets are supplied, only
those targets will be checked.

=item B<-u, --update>

Update foreign packages in the AUR. Without any arguments, all manually
installed packages will be updated. If targets are supplied, only those targets
will be updated.

=item B<-v, --version>

Display version and quit.

=item B<-h, --help>

Display the help message and quit.

=back


=head1 OPTIONS

=over 4

=item B<-e, --edit>

Edit I<target>(s) PKGBUILD and view install script when downloading or building
target(s). Can also be used as a standalone command.

=item B<-c, --clean>

Remove I<target>(s) build files after building target(s). Pass this option twice
to force cleaning when the cleandevel option is disabled. Can also be used as a
standalone command. When passed twice without any arguments, clean the entire
build directory.

=item B<-q, --quiet>

Show less information for search and query operations. Search will only show
package names and not version, group, and description information.

=item B<-a, --aur>

When used with pacman extended operations, only search or install packages from
the AUR.

=item B<-r, --repo>

When used with pacman extended operations, only search or install packages from
the repositories.

=item B<-f, --force>

Overwrite existing files when downloading.

=item B<--devel>

When used with update operations, also upgrade AUR development packages
(supported are cvs, svn, git, hg, bzr and darcs development packages).
The build of development packages that are found up-to-date after the source
checkout will be skipped.

=item B<--ignore> I<package(s)>

Ignore a package upgrade. Can be used more than once. Also accepts a comma
delimited list as a single argument. Packages listed in pacman and cower's
IgnorePkg directive are honored.

=item B<--noconfirm>

Perform commands without confirmation from the user.

=item B<--noedit>

Perform commands without editing any installation files. Bypass I<--edit> option.

=item B<--rebuild>

Always rebuild package(s) regardless of any existing file in I<$PKGDEST> directory,
and regardless of up-to-date status of development packages.

=item B<--ignore-ood>

When searching the AUR, ignore all results marked as out of date.

=item B<--no-ignore-ood>

When searching the AUR, also show results marked as out of date. This take
precedence over the I<IgnoreOOD> option of the cower config file.

=item B<--insecure>
Temporarily enable the bash dependency solver for packages that do not have AUR
metadata info and which may not provide correct dependencies information through
the extended AUR API. All packages uploaded to the AUR before 2014-05-27 18:35 UTC
(AUR 3.0.0 release) are concerned and should be reuploaded by their respective
maintainers. A notice will however be shown before sourcing if potentially harmful
pseudo code is detected. In normal mode, a warning will be displayed if packages
are missing AUR metadata.

=item B<--preview>
When using the bash dependency solver, allow to preview PKGBUILDs before sourcing
for dependency information. Use in conjunction with the I<--insecure> option.

=back


=head1 CONFIG FILE

=over 4

=item B<system config>

Pacaur honors a system-wide config file which will be looked for first at

  $XDG_CONFIG_DIRS/pacaur/config

and falling back to

  /etc/xdg/pacaur/config

=item B<user config>

User-defined configuration files overriding the general settings will be looked
for first at

  $XDG_CONFIG_HOME/pacaur/config

and falling back to

  $HOME/.config/pacaur/config

=item B<other config>

In addition, pacaur fully honors cower config file. See B<cower>(1).

=back

=head1 CONFIG OPTIONS

The available options are:

=over 4

=item B<builddir>

Define the build directory. Default is B<$BUILDDIR>, with a fallback on
I</tmp/pacaurtmp-$USER>.

=item B<editor>

Define the editor. Default is B<$EDITOR>, with a fallback on I<vi>.

=item B<editpkgbuild>

Enable PKGBUILD editing prompt. Default is B<true>.

=item B<editinstall>

Enable install script editing prompt. Default is B<true>.

=item B<fallback>

Extend pacman commands to the AUR. Default is B<true>.

=item B<clean>

Clean build directory after operation. Default is B<true>.

=item B<cleandevel>

When clean config option is enabled, clean build directory of development
packages. Default is B<true>.

=item B<sudoloop>

Prevent sudo timeout. This option overrides the system-wide sudo configuration.
Default is B<false>.

=item B<sortbyvotes>

When searching the AUR, sort the results by decreasing number of votes. Default
is B<true>.

=back

=head1 NOTES

=over 4

=item B<sudo configuration>

To be used with minimal password prompting, I<sudo> should be configured
accordingly. See B<sudoers>(5). Alternatively, enable the I<sudoloop> config
option. This option will override the system-wide sudo configuration and
refresh the sudo timestamp automatically when building packages.

=item B<colored output>

Colored output can be enabled with the I<Color> misc option in I<pacman.conf>.

=item B<detailed interface>

An interface which displays name, version and size of target packages formatted
as a table can be enabled with the I<VerbosePkgLists> misc option in
I<pacman.conf>.

=item B<environment variables>

Makepkg environment variables (I<$PACMAN>, I<$PKGDEST>, I<$SRCDEST>,
I<$BUILDDIR>) are fully honored. See B<makepkg>(8).

=item B<build directory>

You might want to change the default build directory (set on /tmp on a temporary
filesystem residing in volatile memory) especially when building big packages on
a low-memory machine.

=item B<build cleaning>

If you want to avoid cleaning up the build directory of packages, disable the
I<clean> config option. If you want to avoid cleaning up the build directory of
development packages, disable the I<cleandevel> config option. This will speed
up the update even if the I<clean> config option is enabled for normal packages.
You might also want to change the default temporary directory which is
automatically cleared upon reboot.

=item B<host name error>

If a lot of "Couldn't resolve host name" and "Timeout was reached" messages are
outputed while checking for updates in spite of the internet line working
correctly, ensure your local I<DNS server> is correctly configured to improve
queries speed. Using Google primary DNS (8.8.8.8 and 8.8.4.4) might also help.

=item B<alternative installation root>

The alternative installation root I<--root /path> option of pacman is not
supported. You might want to chroot to the new path and use pacaur from there
instead.


=back

=head1 SEE ALSO

B<cower>(1), B<pacman>(8), B<makepkg>(8), B<sudoers>(5)


=head1 AUTHOR

Remy Marquis E<lt>remy.marquis@gmail.comE<gt>

All credits go to all direct or indirect contributors. Many thanks to all of you!

=head1 TRANSLATORS

B<[de] - Deutsch> - Marco "BigBoot" Kirchner, "pszalanski"

B<[es] - Español> - Germán "gosella" Osella Massa

B<[fr] - Français> - "spider-mario", "Neitsab"

B<[it] - Italiano> - Demenico "NoMore201" Lezzi

B<[ja] - 日本語> - Colin "fosskers" Woodbury

B<[pl] - Polski> - Tomasz "Ludvick" Niedzielski

B<[ru] - Русский> - "kyak"
