=encoding utf8

=head1 NAME

pacaur - a fast workflow AUR helper using cower as backend

=head1 SYNOPSIS

Usage: I<pacaur> E<lt>operationE<gt> [ options ] [ target(s) ]

=head1 DESCRIPTION

Pacaur is an Arch User Repository (AUR) helper aiming at speed and simplicity,
designed to minimize user prompt interaction and to use an uncluttered
interface. It is built upon the well designed cower and expac C backends.

Invoking pacaur consists of supplying an operation, any applicable options, and
usually one or more targets. A I<target> is usually a package name or a search
string.

=head1 USERBASE TARGET

Pacaur is targeted at B<advanced users> who want some degree of automation for
repetitive tasks. As such, the user is expected to be familiar with the AUR
manual build process with makepkg and its configuration options, as well as
being knownledgeable about sudo configuration.

Two sets of command line options are provided: commands which call the pacman
binary and extend for AUR functions B<(-S, -Q)>, and commands which are AUR
specific B<(-s, -i, -d, -m, -y, -k, -u)>. As such, pacaur can be used by users
who prefer to have a single tool to manage officials and AUR repositories, or by
users who prefer to keep their AUR frontend separated from pacman.

=head1 OPERATIONS

=over 4

=item B<-S, -Ss, -Si, -Sii, -Sw, -Su, -Qu, -Sc, -Scc>

Pacaur wraps B<pacman operations> and extends respectively its install, search,
info, download, update, check updates and clean functions to the AUR. This
behavior is optional and can be disabled with the I<fallback> variable in the
config file. Pacaur will also pass any pacman related options to the pacman
binary.

=item B<-s, --search>

Search for packages with the I<target(s)> as the search term(s). Queries with
multiple targets will return the result of the intersection of all query
results. Extended regex patterns as defined by POSIX are allowed.

=item B<-i, --info>

Show info for I<target(s)>.

=item B<-d, --download>

Download I<target(s)> PKGBUILD. Pass this option twice to fetch dependencies
(done recursively).

=item B<-m, --makepkg>

Download PKGBUILD and build I<target(s)>. Missing dependencies will be installed
as required to ensure the build to succeed, before being automatically
uninstalled.

=item B<-y, --sync>

Download PKGBUILD, build and install I<target(s)>. Missing dependencies will be
automatically installed as required.

=item B<-k, --check>

Check foreign packages for updates in the AUR. Without any arguments, all
manually installed packages will be checked. If I<target(s)> are supplied, only
those packages will be checked.

=item B<-u, --update>

Update foreign packages in the AUR. Without any arguments, all manually
installed packages will be updated. If I<target(s)> are supplied, only those
packages will be updated.

=item B<-v, --version>

Display version and quit.

=item B<-h, --help>

Display the help message and quit.

=back


=head1 OPTIONS

=over 4

=item B<-e, --edit>

Edit PKGBUILD and view install script when downloading or building I<target(s)>.
Can also be used as a standalone command.

=item B<-c, --clean>

Remove build files after building I<target(s)>. Pass this option twice to force
cleaning when the cleandevel option is disabled. Can also be used as a
standalone command. When passed twice without any arguments, clean the entire
build directory.

=item B<-q, --quiet>

Show less information for search and query operations. Search will only show
package names and not version, group, and description information.

=item B<-a, --aur>

When used with pacman extended operations, only search or install I<target(s)>
from the AUR.

=item B<-r, --repo>

When used with pacman extended operations, only search or install I<target(s)>
from the repositories.

=item B<-f, --force>

Overwrite existing files when downloading I<target(s)> PKGBUILD.

=item B<--devel>

When used with update operations, also upgrade AUR development packages
(supported are cvs, svn, git, hg, bzr and darcs development packages).

=item B<--ignore> I<target(s)>

Ignore a I<target> upgrade. Can be used more than once. Also accepts a comma
delimited list as a single argument. Packages listed in pacman and cower's
IgnorePkg directive are honored.

=item B<--needed>

Do not reinstall I<target(s)> that are already up to date. The build of
development packages that are found up-to-date after the source checkout will
also be skipped.

=item B<--noconfirm>

Perform commands without confirmation from the user.

=item B<--noedit>

Perform commands without editing any installation files. Bypass the I<--edit>
option.

=item B<--rebuild>

Always rebuild packages regardless of any existing file in I<$PKGDEST> directory.

=item B<--ignore-ood>

When searching the AUR, ignore all results marked as out of date.

=item B<--no-ignore-ood>

When searching the AUR, also show results marked as out of date. This take
precedence over the I<IgnoreOOD> option of the cower config file.

=item B<--insecure (temporary)>

Temporarily enable the bash dependency solver for packages that do not have AUR
metadata and which may not provide correct dependencies information through the
extended AUR API. A notice will however be shown before sourcing if potentially
harmful pseudo code is detected.

=item B<--preview (temporary)>

When using the bash dependency solver, allow to preview PKGBUILDs before sourcing
for dependency information. Use in conjunction with the I<--insecure> option.

=back


=head1 CONFIG FILE

=over 4

=item B<system config>

Pacaur honors a system-wide config file which will be looked for first at

  $XDG_CONFIG_DIRS/pacaur/config

and falling back to

  /etc/xdg/pacaur/config

=item B<user config>

User-defined configuration files overriding the general settings will be looked
for first at

  $XDG_CONFIG_HOME/pacaur/config

and falling back to

  $HOME/.config/pacaur/config

=item B<other config>

In addition, pacaur fully honors cower config file. See B<cower>(1).

=back

=head1 CONFIG OPTIONS

The available options are:

=over 4

=item B<builddir>

Define the build directory. Default is I<$BUILDDIR>, with a fallback on
B</tmp/pacaurtmp-$USER>.

=item B<editor>

Define the editor. Default is I<$EDITOR>, with a fallback on B<vi>.

=item B<editpkgbuild>

Enable PKGBUILD editing prompt. Default is B<true>.

=item B<editinstall>

Enable install script editing prompt. Default is B<true>.

=item B<fallback>

Extend pacman commands to the AUR. Default is B<true>.

=item B<clean>

Clean build directory after operation. Default is B<true>.

=item B<cleandevel>

When clean config option is enabled, clean build directory of development
packages. Default is B<true>.

=item B<sortbyvotes>

When searching the AUR, sort the results by decreasing number of votes. Default
is B<true>.

=item B<sudoloop>

Prevent sudo timeout. This option overrides the system-wide sudo configuration
and refresh the sudo timestamp automatically in a loop when building packages.
Default is B<false>.

=back

=head1 NOTES

=over 4

=item B<secure solver vs hybrid solver>

Since version 4.2, pacaur solves the dependency tree using the full secured
extended RPC AUR interface. Packages which are missing AUR metadata may however
not provide correct dependencies information and a warning will be displayed.

All packages uploaded to the AUR before 2014-05-27 18:35 UTC (AUR 3.0.0 release)
are concerned and should be reuploaded by their respective maintainers. If you
encounter such packages, please notify their maintainer about their missing AUR
metadata status.

It is however possible to temporarily enable the old parsing dependency solver
for such packages with the I<--insecure> option, while the additional I<--preview>
option allows to preview PKGBUILDs before sourcing for dependency information.

Both of these options are temporary only and will be removed in the near future.

=item B<sudo configuration>

To be used with minimal password prompting, I<sudo> should be configured
accordingly. See B<sudoers>(5). Alternatively, enable the I<sudoloop> config
option.

=item B<pacman misc options>

Miscellaneous options enabled in I<pacman.conf> are taken into account. Thus,
colored output can be enabled with the I<Color> option, while a detailed interface
displaying name, version and size of packages formatted as a table is available
through the I<VerbosePkgLists> option.

=item B<environment variables>

Makepkg environment variables (I<$PACMAN>, I<$PKGDEST>, I<$SRCDEST>,
I<$BUILDDIR>) are fully honored. See B<makepkg>(8).

=item B<build directory>

You might want to change the default build directory (set on /tmp on a temporary
filesystem residing in volatile memory) especially when building big packages on
a low-memory machine.

=item B<build cleaning>

If you want to avoid cleaning up the build directory of packages, disable the
I<clean> config option. If you want to avoid cleaning up the build directory of
development packages, disable the I<cleandevel> config option. This will speed
up the update even if the I<clean> config option is enabled for normal packages.
You might also want to change the default temporary directory which is
automatically cleared upon reboot. Alternatively, you can enable source caching
with the makepkg I<$SRCDEST> environment variable.

=item B<build without installing>

If you want to build packages without installing them, you should ensure that
the makepkg I<$PKGDEST> environment variable is set or that the I<clean> option
is disabled in order to avoid the packages to be deleted after being built.

=item B<interactive PKGBUILDs>

Packages requiring user input while building are not supported and might fail
to install properly. There are currently no official directive about these
interactives PKGBUILDs, but some of the official pacman developers expressed
the opinion that PKGBUILDs should always provide default compilation options.

=item B<host name error>

If a lot of "Couldn't resolve host name" and "Timeout was reached" messages are
outputed while checking for updates in spite of the internet line working
correctly, ensure your local I<DNS server> is correctly configured to improve
queries speed. Using Google primary DNS (8.8.8.8 and 8.8.4.4) might also help.

=item B<alternative installation root>

The alternative installation root I<--root /path> option of pacman is not
supported. You might want to chroot to the new path and use pacaur from there
instead.


=back

=head1 SEE ALSO

B<cower>(1), B<pacman>(8), B<makepkg>(8), B<sudoers>(5)


=head1 AUTHOR

Remy Marquis E<lt>remy.marquis@gmail.comE<gt>

All credits go to all direct or indirect contributors. Many thanks to all of you!

=head1 TRANSLATORS

B<[de] - Deutsch> - Marco "BigBoot" Kirchner, "pszalanski", Stefan "rumpelsepp" Tatschner

B<[es] - Español> - Germán "gosella" Osella Massa

B<[fr] - Français> - "spider-mario", "Neitsab"

B<[it] - Italiano> - Demenico "NoMore201" Lezzi

B<[ja] - 日本語> - Colin "fosskers" Woodbury

B<[pl] - Polski> - Tomasz "Ludvick" Niedzielski

B<[pt] - Português> - Thiago "thiagowfx" Barroso Perrotta

B<[ru] - Русский> - "kyak"
